### ISSUE TITLE
Image classification: ValueError on fetch

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#108]
Setting image_classification = 1 in a properties file and then trying to fetch images in Classifier using  fef5481beb6575e04fae0fdf2f938706ce158c8a yields the following error:
```
An error occurred in the program:
ValueError: empty range for randrange() (1,1, 0)

Traceback (most recent call last):
  File "C:\Trunk\pull_requests\CellProfiler-Analyst\cpa\classifier.py", line 841, in OnFetch
    obKeys = dm.GetRandomObjects(nObjects)
  File "C:\Trunk\pull_requests\CellProfiler-Analyst\cpa\datamodel.py", line 119, in GetRandomObjects
    return [self.GetRandomObject() for i in xrange(N)]
  File "C:\Trunk\pull_requests\CellProfiler-Analyst\cpa\datamodel.py", line 97, in GetRandomObject
    obIdx = randint(1, self.obCount)
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
```

**Comment by jhung0** [comment]
should be fixed

**Comment by jhung0** [comment]
Is it fixed?

**Comment by braymp** [comment]
Yes, it seems to be fixed.
