### ISSUE TITLE
Error in specifying a filter to fetch images in image gallery 

### ISSUE THREAD

**Issue by mrohban** [CellProfiler/CellProfiler-Analyst#128]
I created the following query to fetch images based on a combination of metadata features:
![screen shot 2016-01-20 at 12 18 13 pm](https://cloud.githubusercontent.com/assets/11319440/12457045/7f0a0794-bf70-11e5-97cb-f07503372b6b.png)

when trying to fetch, I get this error: 

An error occurred in the program:
Exception: Filter query failed for filter "AKTCluster". Check the MySQL syntax in your properties file.

Traceback (most recent call last):
  File "wx/_core.pyc", line 16766, in <lambda>
  File "/Users/mrohban/Downloads/CellProfiler Analyst-2.app/Contents/Resources/lib/python2.7/cpa/imagegallery.py", line 474, in cb
  File "/Users/mrohban/Downloads/CellProfiler Analyst-2.app/Contents/Resources/lib/python2.7/cpa/dbconnect.py", line 781, in GetFilteredImages

**Comment by daviddao** [comment]
Fixed with  b7449a8
