### ISSUE TITLE
AttributeError during ScoreAll

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#130]
* Open the cpa_example props file.
* Load the example training set
* Train using the default RandomForest

"Score all" with the defaults produces the error below.
```
An error occurred in the program:
AttributeError: 'numpy.float64' object has no attribute 'split'

Traceback (most recent call last):
  File "C:\Trunk\cellProfiler-analyst\cpa\classifier.py", line 1555, in ScoreAll
    self.keysAndCounts = self.algorithm.PerImageCounts(number_of_classes, filter, update)
  File "C:\Trunk\cellProfiler-analyst\cpa\generalclassifier.py", line 109, in PerImageCounts
    return multiclasssql.PerImageCounts(self, number_of_classes, filter_name, cb)
  File "C:\Trunk\cellProfiler-analyst\cpa\multiclasssql.py", line 266, in PerImageCounts
    counts = do_by_steps(p.object_table, filter_name, p.area_scoring_column)
  File "C:\Trunk\cellProfiler-analyst\cpa\multiclasssql.py", line 247, in do_by_steps
    cell_data = np.reshape(np.genfromtxt(cell_data.flatten()), data_shape)
  File "C:\Python27\lib\site-packages\numpy\lib\npyio.py", line 1479, in genfromtxt
    first_values = split_line(first_line)
  File "C:\Python27\lib\site-packages\numpy\lib\_iotools.py", line 219, in _delimited_splitter
    line = line.split(self.comments)[0]
```

**Comment by jhung0** [comment]
fixed with c97ae49
