### ISSUE TITLE
Scatter plot error

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#150]
This is for ImageNumber vs. ImageNumber. The first plot (linear linear) appeared fine. Then I changed linear to log and kept getting this message after updating (even when I changed everything back to linear linear) :

An error occurred in the program:
ValueError: posx and posy should be finite values

Traceback (most recent call last):
  File "/Users/jyhung/Documents/work/CellProfiler-Analyst/cpa/scatter.py", line 280, in update_figpanel
    self.update_gate_helper()
  File "/Users/jyhung/Documents/work/CellProfiler-Analyst/cpa/scatter.py", line 222, in update_gate_helper
    self.figpanel.gate_helper.disable()
  File "/Users/jyhung/Documents/work/CellProfiler-Analyst/cpa/gating.py", line 64, in disable
    self.canvas.draw()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_wxagg.py", line 51, in draw
    FigureCanvasAgg.draw(self)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 474, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1133, in draw
    func(*args)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2304, in draw
    a.draw(renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axis.py", line 1120, in draw
    self.label.draw(renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/text.py", line 757, in draw
    raise ValueError("posx and posy should be finite values")

**Comment by braymp** [comment]
Duplicate of #97?

**Comment by jhung0** [comment]
yes but before it wasn't an issue on mac...now it's back
