### ISSUE TITLE
ImageGallery: Error if requesting objects from unselected image

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#163]
To reproduce:
* Load cpa_example
* Start ImageGallery, fetch an image
* Right-click on the image tile (without selecting it) and select "Fetch all objects from image"
The following error comes up:
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16766, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Trunk\cellProfiler-analyst\cpa\imagetile.py", line 140, in cb
    imKey = pseudo_obKeys[0][:-1] # Get image key
IndexError: list index out of range
```

**Comment by daviddao** [comment]
Added a warning with 688053a
