### ISSUE TITLE
More helpful msg if "Score all" fails

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#176]
On my classification problem, I only have 3 images. On "Score all", CPA logs
```
INFO:root:time to calculate hits: 0.000s
INFO:root:time to group per-image counts: 0.001s
INFO:root:Fitting beta binomial distribution to data...
INFO:root:   alpha = [ nan  nan]   converged = True
INFO:root:   alpha/Sum(alpha) = [nan, nan]
INFO:root:time to fit beta binomial: 0.006s
INFO:root:Computing enrichment scores for each group...
INFO:root:time to compute enrichment scores: 0.001s
```
which I assume means that enrichment score computation failed. CPA then produces the error:
```
Traceback (most recent call last):
  File "C:\Users\brayma2\Desktop\GitHub\CellProfiler-Analyst\cpa\classifier.py", line 1724, in ScoreAll
    grid.table_from_array(tableData, labels, group, key_col_indices)
  File "C:\Users\brayma2\Desktop\GitHub\CellProfiler-Analyst\cpa\tableviewer.py", line 715, in table_from_array
    table_base = PlainTable(self, data, col_labels, key_indices, grouping)
  File "C:\Users\brayma2\Desktop\GitHub\CellProfiler-Analyst\cpa\tableviewer.py", line 174, in __init__
    assert len(col_labels) == data.shape[1], "Number of column labels does not match the number of columns in data."
AssertionError: Number of column labels does not match the number of columns in data.
```
The fact that CPA couldn't calculate the enrichment scores is fine (and expected?). But a more helpful dialog stating that fact would be nice.

**Comment by jhung0** [comment]
Can you try now?

**Comment by braymp** [comment]
Is there a recent commit that corrects the problem; I don't see anything new...

**Comment by jhung0** [comment]
sorry should be there now

**Comment by braymp** [comment]
Yep, it's good.
