### ISSUE TITLE
Save properties error, related to version_number

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler-Analyst#187]
Got the error below in CPA 2.2.1 when choosing File > Save Properties. A named file is saved to the desired location, but the file is completely empty.

An error occurred in the program:
AttributeError: 'module' object has no attribute 'version_number'

Traceback (most recent call last):
  File "/Applications/CellProfiler Analyst.app/Contents/Resources/CellProfiler-Analyst.py", line 315, in on_save_properties
    p.save_file(dlg.GetPath())
  File "/Applications/CellProfiler Analyst.app/Contents/Resources/lib/python2.7/cpa/properties.py", line 363, in save_file
    **version** = util.version.version_number

**Comment by jhung0** [comment]
b92aeba I don't know much about the version number, so I just commented that part out
