### ISSUE TITLE
Fetching random cell from image doesn't work

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#203]
An error occurred in the program:
TypeError: Required argument 'to' (pos 3) not found

Traceback (most recent call last):
  File "/Users/jyhung/Documents/work/CellProfiler-Analyst/cpa/classifier.py", line 1776, in OnSelectFilter
    self.SetupFetchFromGroupSizer(filter)
  File "/Users/jyhung/Documents/work/CellProfiler-Analyst/cpa/classifier.py", line 1824, in SetupFetchFromGroupSizer
    fieldInp.SetSelection(0)
  File "/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 13281, in SetSelection
    return _core_.TextEntryBase_SetSelection(*args, **kwargs)

**Comment by jhung0** [comment]
Filters work but the problem is if you choose fetch x x cells from image

**Comment by daviddao** [comment]
Should be fixed with 	993dec4. The issue was a different API due to wx3: TextCtrl's `SetSelection(0)` needs to be replaced with `SetSelection(-1,-1)`. Also `GetStringSelection()` returns an empty string. We need to directly access string values with `.Value()`. Annoying.
