### ISSUE TITLE
Error in Normalization Tool: AGG_CHOICES.remove(M_NEGCTRL)

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler-Analyst#230]
Using CP 2.1.1, load the example database and properties file.  Go to Tools > Normalization Tool. Click Image_OrigThreshold_DNA and click Perform Normalization.  The error below results.

It is possible that there is user error here (i.e. something needs to be set up in properties file in order for this to work properly, or the settings I chose make no sense) but if so, a warning and description should be provided.

An error occurred in the program:
ValueError: list.remove(x): x not in list

Traceback (most recent call last):
  File "/Applications/CellProfiler Analyst.app/Contents/Resources/lib/python2.7/cpa/normalizationtool.py", line 302, in on_add_norm_step
    self.add_norm_step()
  File "/Applications/CellProfiler Analyst.app/Contents/Resources/lib/python2.7/cpa/normalizationtool.py", line 336, in add_norm_step
    self.norm_steps += [NormalizationStepPanel(self.sw)]
  File "/Applications/CellProfiler Analyst.app/Contents/Resources/lib/python2.7/cpa/normalizationtool.py", line 42, in __init__
    AGG_CHOICES.remove(M_NEGCTRL)

**Comment by daviddao** [comment]
Hi Anne,
Yes, that is due to the early development of a negative control normalization procedure for profiling purpose. I will take a look! Thanks for reporting and checking the normalization tool!
