### ISSUE TITLE
Error using CPA from source 

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#236]
python CellProfiler-Analyst.py 
Traceback (most recent call last):
  File "CellProfiler-Analyst.py", line 19, in <module>
    import javabridge
  File "/usr/local/lib/python2.7/site-packages/javabridge/**init**.py", line 28, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/usr/local/lib/python2.7/site-packages/javabridge/jutil.py", line 18, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/site-packages/numpy/**init**.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/**init**.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/site-packages/numpy/core/__init__.py", line 58, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/__init__.py", line 12, in <module>
    from . import decorators as dec
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/decorators.py", line 21, in <module>
    from .utils import SkipTest
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so

**Comment by jhung0** [comment]
@daviddao does it work for you?

**Comment by daviddao** [comment]
Let me check. I have the feeling it could be wxPython's fault.

**Comment by jhung0** [comment]
Brew only has 3.0.2.0 available, and I don't know if 2.8 is available somewhere else...

**Comment by dlogan** [comment]
Yeah, I can't find wxpython 2.8, or any version less than 3.0.2 via brew.

**Comment by daviddao** [comment]
I will try to fix CPA this week. But in the long-term we should really get rid of wxPython! It an unreliable dependency.

**Comment by jhung0** [comment]
Yeah at the retreat we talked about this (though I didn't think it would
come up so soon)...but how do we fix the entanglement with wxPython?

**Comment by daviddao** [comment]
Were you able to fix it?

**Comment by jhung0** [comment]
forcing wx 2.8 solved it I think

**Comment by dlogan** [comment]
How did you force wx 2.8 installation?

**Comment by jhung0** [comment]
Oh I didn't...it was just your change that made it work again
