### ISSUE TITLE
CPA crashed on old-style filter definitions

### ISSUE THREAD

**Issue by ljosa** [CellProfiler/CellProfiler-Analyst#24]
Some properties files define old-style filters in the following way:

```
filters  =  MCF7wt
```

This no longer works: it causes CPA to crash on startup with console messages such as this:

```
2012-06-14 9:26:11.410 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst: WARNING:root:PROPERTIES WARNING: Unrecognized field "" in properties file
2012-06-14 9:26:11.410 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst: Traceback (most recent call last):
2012-06-14 9:26:11.410 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst:   File "/Volumes/CPA_dist/CPAnalyst.app/Contents/Resources/__boot__.py", line 312, in <module>
2012-06-14 9:26:11.410 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst:     _run('cpa.py')
2012-06-14 9:26:11.410 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst:   File "/Volumes/CPA_dist/CPAnalyst.app/Contents/Resources/__boot__.py", line 309, in _run
2012-06-14 9:26:11.410 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst:     execfile(path, globals(), globals())
2012-06-14 9:26:11.410 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst:   File "/Volumes/CPA_dist/CPAnalyst.app/Contents/Resources/cpa.py", line 529, in <module>
2012-06-14 9:26:11.411 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst:     app = CPAnalyst(redirect=False)
2012-06-14 9:26:11.411 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst:   File "wx/_core.pyc", line 7978, in __init__
2012-06-14 9:26:11.411 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst:   File "wx/_core.pyc", line 7552, in _BootstrapApp
2012-06-14 9:26:11.411 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst:   File "/Volumes/CPA_dist/CPAnalyst.app/Contents/Resources/cpa.py", line 447, in OnInit
2012-06-14 9:26:11.411 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst:     if not show_load_dialog():
2012-06-14 9:26:11.411 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst:   File "guiutils.pyc", line 814, in show_load_dialog
2012-06-14 9:26:11.411 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst:   File "properties.pyc", line 269, in load_file
2012-06-14 9:26:11.412 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst:   File "<string>", line 1, in <module>
2012-06-14 9:26:11.412 AM [0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst: NameError: name 'MCF7wt' is not defined
2012-06-14 9:26:11.431 AM CPAnalyst: CPAnalyst Error
2012-06-14 9:26:14.210 AM com.apple.launchd.peruser.1104423985: ([0x0-0xe60e6].org.pythonmac.unspecified.CPAnalyst[84035]) Exited with code: 255
```

CPA should handle these old-style filter definitions.

I have committed a unit test for this (6044434436a8f03e3751fc27186f6c6691ef9436). Run with `nosetests cpa.tests.test_properties:test_old_filter`.

**Comment by DavidStirling** [comment]
Closing as stale
