### ISSUE TITLE
DBException when trying to Show images in gate (montage)

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler-Analyst#246]
Works fine in stable, but fails in master; doesn't happen with `Show images in gate`, just `Show images in gate (montage)`, so maybe related to 80f7807679fb3f44c6a4eece6d8abc3ce63cef90 ?
```
An error occurred in the program:
DBException: ERROR: Database query failed for connection "MainThread" and failed to reconnect
Query was: "SELECT name FROM sqlite_master WHERE type="table" ORDER BY name"
First exception was: database is locked
Second exception was: ERROR: Database query failed for connection "MainThread"
Query was: "SELECT name FROM sqlite_master WHERE type="table" ORDER BY name"
Exception was: database is locked



Traceback (most recent call last):
  File "C:\Users\bcimini\GitHub\CellProfiler-Analyst\cpa\scatter.py", line 529, in show_objects_from_gate
    ui.show_objects_from_gate(gatename)
  File "C:\Users\bcimini\GitHub\CellProfiler-Analyst\cpa\guiutils.py", line 766, in show_objects_from_gate
    keys = db.execute(str(q))
  File "C:\Users\bcimini\GitHub\CellProfiler-Analyst\cpa\sqltools.py", line 46, in __str__
    from_clause = self.get_from_clause()
  File "C:\Users\bcimini\GitHub\CellProfiler-Analyst\cpa\sqltools.py", line 135, in get_from_clause
    return ', '.join(self.get_tables() + self.old_filters)
  File "C:\Users\bcimini\GitHub\CellProfiler-Analyst\cpa\sqltools.py", line 129, in get_tables
    exps = db.get_linking_expressions(tables)
  File "C:\Users\bcimini\GitHub\CellProfiler-Analyst\cpa\dbconnect.py", line 946, in get_linking_expressions
    if self.get_linking_table_pairs(tables[0], t) is None:
  File "C:\Users\bcimini\GitHub\CellProfiler-Analyst\cpa\dbconnect.py", line 986, in get_linking_table_pairs
    ltables = self.get_linking_tables(table_from, table_to)
  File "C:\Users\bcimini\GitHub\CellProfiler-Analyst\cpa\dbconnect.py", line 969, in get_linking_tables
    if p.link_tables_table not in self.GetTableNames():
  File "C:\Users\bcimini\GitHub\CellProfiler-Analyst\cpa\dbconnect.py", line 797, in GetTableNames
    res = self.execute('SELECT name FROM sqlite_master WHERE type="table" ORDER BY name')
  File "C:\Users\bcimini\GitHub\CellProfiler-Analyst\cpa\dbconnect.py", line 64, in fn
    return f(db, *args, **kwargs)
  File "C:\Users\bcimini\GitHub\CellProfiler-Analyst\cpa\dbconnect.py", line 529, in execute
    '\nSecond exception was: %s'%(connID, query, e, e2))
```

**Comment by jhung0** [comment]
Does this still happen? It worked fine when I tried.

**Comment by bethac07** [comment]
Just tried, works ok now.  Will close.
