### ISSUE TITLE
Problem running CP from source on Windows

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler-Analyst#253]
When I try to run either `master` or `stable` from source, after selecting the properties file I get the following error:

```
INFO:root:[MainThread] Connecting to the database...
INFO:root:[MainThread] SQLite file: C:\Users\bcimini\Desktop\Cleanup\2017_09_13_NEUBIAS\TranslocationOutput\DefaultDB.dbTraceback (most recent call last):
  File ".\CellProfiler-Analyst.py", line 553, in <module>
    app.Start()
  File ".\CellProfiler-Analyst.py", line 472, in Start
    log4j.basic_config()
  File "C:\Python27\lib\site-packages\bioformats\log4j.py", line 12, in basic_config
    javabridge.JClassWrapper("loci.common.Log4jTools").enableLogging("WARN")
  File "C:\Python27\lib\site-packages\javabridge\wrappers.py", line 196, in <lambda>
    fn = lambda naame=name: lambda *args: self.__call_static(naame, *args)
  File "C:\Python27\lib\site-packages\javabridge\wrappers.py", line 284, in __call_static
    raise TypeError("No matching method found for %s" % method_name)
TypeError: No matching method found for enableLogging
```

My pip freeze is below, if it helps.

```
alabaster==0.7.10
astroid==1.4.9
Babel==2.3.4
backports-abc==0.5
backports.functools-lru-cache==1.3
backports.shutil-get-terminal-size==1.0.0
bleach==2.0.0
boto3==1.4.4
botocore==1.5.32
cellh5==1.3.0
centrosome==1.0.8
certifi==2017.1.23
chardet==2.3.0
colorama==0.3.7
configparser==3.5.0
contextlib2==0.5.4
cycler==0.10.0
Cython==0.25.2
dask==0.14.0
decorator==4.1.2
docutils==0.13.1
entrypoints==0.2.2
enum34==1.1.6
functools32==3.2.3.post2
future==0.16.0
futures==3.0.5
h5py==2.6.0
hmmlearn==0.2.0
html5lib==0.999999999
imagesize==0.7.1
inflect==0.2.5
ipykernel==4.5.2
ipython==5.3.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
isort==4.2.5
javabridge==1.0.15
jedi==0.9.0
Jinja2==2.9.5
jmespath==0.9.2
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.0.0
jupyter-console==5.1.0
jupyter-core==4.3.0
lazy-object-proxy==1.2.2
libtiff==0.4.0
lxml==3.7.3
mahotas==1.4.3
MarkupSafe==1.0
matplotlib==2.0.2
mccabe==0.6.1
mistune==0.7.4
MySQL-python==1.2.5
nbconvert==5.1.1
nbformat==4.3.0
networkx==1.11
notebook==4.4.1
numpy==1.13.3+mkl
numpydoc==0.6.0
olefile==0.44
pandas==0.19.2
pandocfilters==1.4.1
pathlib2==2.2.1
pep8==1.7.0
pickleshare==0.7.4
Pillow==4.2.1
prokaryote==2.3.0
prompt-toolkit==1.0.13
psutil==5.2.0
py==1.4.33
pyamg==3.1.1
pyflakes==1.5.0
Pygments==2.2.0
pylint==1.6.5
pyparsing==2.2.0
PyQt4==4.11.4
pytest==3.0.7
python-bioformats==1.3.0
python-dateutil==2.6.1
pytz==2017.2
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.2.1
QtPy==1.2.1
raven==6.0.0
requests==2.13.0
rope==0.10.5
s3transfer==0.1.10
scandir==1.5
scikit-image==0.13.0
scikit-learn==0.18.1
scipy==0.19.1
seaborn==0.7.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
spyder==3.1.3
testpath==0.3
toolz==0.8.2
tornado==4.4.2
traitlets==4.3.2
typing==3.6.2
verlib==0.1
wcwidth==0.1.7
webencodings==0.5
widgetsnbextension==2.0.0
win-unicode-console==0.5
wrapt==1.10.10
wxPython==3.0.2.0
wxPython-common==3.0.2.0
```

**Comment by bethac07** [comment]
Seems to be related to https://github.com/CellProfiler/python-bioformats/issues/89 , so I'll close and check again after the next python-bioformats release.
