### ISSUE TITLE
Scatter plot error

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler-Analyst#255]
An error occurred in the program:
AttributeError: 'CustomNavToolbar' object has no attribute '_NTB2_PAN'

Traceback (most recent call last):
  File "CellProfiler-Analyst.py", line 271, in launch_scatter_plot
    scatter = Scatter(parent=self)
  File "/Users/jyhung/Documents/com/github/CellProfiler-Analyst/cpa/scatter.py", line 958, in __init__
    self.SetToolBar(figpanel.get_toolbar())
  File "/Users/jyhung/Documents/com/github/CellProfiler-Analyst/cpa/scatter.py", line 902, in get_toolbar
    self.navtoolbar = CustomNavToolbar(self.canvas)
  File "/Users/jyhung/Documents/com/github/CellProfiler-Analyst/cpa/scatter.py", line 1011, in __init__
    self.PAN = self.wx_ids['Pan']  if mpl_version.split('.')[1] >= '2' else self._NTB2_PAN

**Comment by jhung0** [comment]
fixed by 379ea8c938e0eae86f6442264e5f32b01335c101
