### ISSUE TITLE
numpy.ufunc wrong size

### ISSUE THREAD

**Issue by fbenedett** [CellProfiler/CellProfiler-Analyst#269]
Hello,
I am trying to install cellprofiler but I encountered a problem that prevent me to continue.
I have installed all the dependencies written here: https://github.com/CellProfiler/CellProfiler-Analyst/wiki/Dependencies-and-licenses
using pip.  Python wrsion is also 2.7.
I ran:
python setup.py install
from the CellProfiler directory that I have just downloaded with git.
This command seems to work correctly (after some fixing with java version and other missing dependencies) but when I try to run:
cellprofiler
I get the following error:
Traceback (most recent call last):
  File "/home/fbenedet/venv/bin/cellprofiler", line 11, in <module>
    load_entry_point('CellProfiler==2.3.1', 'console_scripts', 'cellprofiler')()
  File "/home/fbenedet/venv/lib/python2.7/site-packages/CellProfiler-2.3.1-py2.7.egg/cellprofiler/__main__.py", line 175, in main
    from cellprofiler.utilities.cpjvm import cp_start_vm
  File "/home/fbenedet/venv/lib/python2.7/site-packages/CellProfiler-2.3.1-py2.7.egg/cellprofiler/utilities/cpjvm.py", line 3, in <module>
    import javabridge
  File "/home/fbenedet/venv/lib/python2.7/site-packages/javabridge-1.0.18-py2.7-linux-x86_64.egg/javabridge/__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "/home/fbenedet/venv/lib/python2.7/site-packages/javabridge-1.0.18-py2.7-linux-x86_64.egg/javabridge/jutil.py", line 157, in <module>
    import javabridge._javabridge as _javabridge
  File "__init__.pxd", line 885, in init _javabridge
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

Any idea on how to fix this?

**Comment by dailihe** [comment]
I ran cellprofiler V319 in python 3.6.3, using pip setup.py install. The same problem occurs. Have you find out the solution? Thx.

**Comment by DavidStirling** [comment]
This is a javabridge compatibility error, will be fixed in 3.0
