### ISSUE TITLE
Can't double click image in ImageGallery to see larger.

### ISSUE THREAD

**Issue by ErinWeisbart** [CellProfiler/CellProfiler-Analyst#275]
Can't double click image in ImageGallery to see larger.
Can see thumbnail and can drag thumbnail into my Classifier so it definitely exists.

An error occurred in the program:
DBException: ERROR: Database query failed for connection "MainThread" and failed to reconnect
Query was: "SELECT Image_Metadata_Plate, Image_Metadata_Well FROM Batch1_QC_Per_Image WHERE Image_Metadata_MasterIndex IN (131)"
First exception was: no such column: Image_Metadata_Well
Second exception was: ERROR: Database query failed for connection "MainThread"
Query was: "SELECT Image_Metadata_Plate, Image_Metadata_Well FROM Batch1_QC_Per_Image WHERE Image_Metadata_MasterIndex IN (131)"
Exception was: no such column: Image_Metadata_Well

Traceback (most recent call last):
  File "cpa\imagetile.pyc", line 177, in OnDClick
  File "cpa\imagetools.pyc", line 73, in ShowImage
  File "cpa\imageviewer.pyc", line 230, in __init__
  File "cpa\imageviewer.pyc", line 258, in SetImage
  File "cpa\imageviewer.pyc", line 241, in AutoTitle
  File "cpa\dbconnect.pyc", line 64, in fn
  File "cpa\dbconnect.pyc", line 525, in execute

**Comment by bethac07** [comment]
We traced this to an error with a script outside CellProfiler-Analyst.
