### ISSUE TITLE
Evaluate error in Classifier after closing evaluation matrix window

### ISSUE THREAD

**Issue by pearlryder** [CellProfiler/CellProfiler-Analyst#296]
Mac OSX 10.15.7

Example properties and database files.

To replicate:
- Open the Classifier window
- Train a classifier using the example training set
- Press Evaluate - should get an evaluation matrix window
- Close the Evaluation Matrix
- Press Evaluate again -- get this error:
<img width="612" alt="Screen Shot 2021-05-03 at 11 11 23 AM" src="https://user-images.githubusercontent.com/28375904/116894652-4dca1980-ac00-11eb-811d-336fe7997ef9.png">

```
An error occurred in the program:
RuntimeError: wrapped C/C++ object of type FigureFrameWxAgg has been deleted

Traceback (most recent call last):
  File "cpa/classifier.py", line 1453, in OnEvaluation
  File "cpa/generalclassifier.py", line 497, in ConfusionMatrix
  File "matplotlib/pyplot.py", line 353, in show
  File "matplotlib/backend_bases.py", line 3524, in show
  File "matplotlib/backends/backend_wx.py", line 1049, in show
```

**Note:** if I don't close the first Evaluation Matrix window, I can keep training and re-evaluating w/o any error.

**Comment by pearlryder** [comment]
This bug also happens when running from source: 
```An error occurred in the program:
RuntimeError: wrapped C/C++ object of type FigureFrameWxAgg has been deleted
Traceback (most recent call last):
  File "/Users/pryder/GitHub/CellProfiler-Analyst/cpa/classifier.py", line 1453, in OnEvaluation
    self.algorithm.ConfusionMatrix(folds)
  File "/Users/pryder/GitHub/CellProfiler-Analyst/cpa/generalclassifier.py", line 497, in ConfusionMatrix
    plt.show()
  File "/Users/pryder/.virtualenvs/CellProfiler-Analyst/lib/python3.8/site-packages/matplotlib/pyplot.py", line 353, in show
    return _backend_mod.show(*args, **kwargs)
  File "/Users/pryder/.virtualenvs/CellProfiler-Analyst/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3524, in show
    manager.show()  # Emits a warning for non-interactive backend.
  File "/Users/pryder/.virtualenvs/CellProfiler-Analyst/lib/python3.8/site-packages/matplotlib/backends/backend_wx.py", line 1049, in show
    self.frame.Show()```
