### ISSUE TITLE
Creating montage from gate/lasso in t-sne reduction

### ISSUE THREAD

**Issue by blin100** [CellProfiler/CellProfiler-Analyst#307]
Hi, great program! I ran into a potential bug trying to make a montage of cells from the t-sne plot. After drawing a gate, or a lasso, and I try to make it, this is the error I receive:

```

An error occurred in the program:
cpa.dbconnect.DBException: ERROR: Database query failed for connection "MainThread" and failed to reconnect
Query was: "SELECT MyExpt_Per_Object.ImageNumber, MyExpt_Per_Object.ObjectNumber 
	FROM MyExpt_Per_Object, pca_table 
	WHERE MyExpt_Per_Object.ObjectNumber = pca_table.ObjectNumber AND MyExpt_Per_Object.ImageNumber = pca_table.ImageNumber AND pca_table.t-SNE_1 BETWEEN "12.624977562818614" AND "33.686474408129214" AND pca_table.t-SNE_2 BETWEEN "64.89471391957161" AND "97.07257903221407" 
	GROUP BY MyExpt_Per_Object.ImageNumber, MyExpt_Per_Object.ObjectNumber"
First exception was: no such column: pca_table.t
Second exception was: ERROR: Database query failed for connection "MainThread"
Query was: "SELECT MyExpt_Per_Object.ImageNumber, MyExpt_Per_Object.ObjectNumber 
	FROM MyExpt_Per_Object, pca_table 
	WHERE MyExpt_Per_Object.ObjectNumber = pca_table.ObjectNumber AND MyExpt_Per_Object.ImageNumber = pca_table.ImageNumber AND pca_table.t-SNE_1 BETWEEN "12.624977562818614" AND "33.686474408129214" AND pca_table.t-SNE_2 BETWEEN "64.89471391957161" AND "97.07257903221407" 
	GROUP BY MyExpt_Per_Object.ImageNumber, MyExpt_Per_Object.ObjectNumber"
Exception was: no such column: pca_table.t



Traceback (most recent call last):
  File "cpa\dimensionreduction.py", line 531, in show_objects_from_gate
  File "cpa\guiutils.py", line 763, in show_objects_from_gate
  File "cpa\dbconnect.py", line 59, in fn
  File "cpa\dbconnect.py", line 525, in execute

```
What I noticed is if you create a gate, and go into gate inspector/manager, the info for the gate seems to be incorrect:

`pca_table.t-SNE_1 BETWEEN "12.624977562818614" AND "33.686474408129214" AND pca_table.t-SNE_2 BETWEEN "64.89471391957161" AND "97.07257903221407"`

It says pca_table.t-SNE, instead of maybe just t-SNE? Not sure if that's the root cause.

Thanks for any assistance you can provide!
Brian

**Comment by DavidStirling** [comment]
Hmm, looks like '-' may not be valid in a table name within the queries. Thanks for reporting this!
