### ISSUE TITLE
Cellprofiler JVM error when opening an image (compiled version)

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-Analyst#40]
Opening an image file, whether via ImageViewer or dbl-clicking a tile in Classifier, produces the following msg:
<pre>
An error occurred in the program:
WindowsError: [Error 3] The system cannot find the path specified: 'D:\\Program Files (x86)\\CellProfiler Analyst_test\\imagej\\jars/*.*'

Traceback (most recent call last):
  File "cpa.py", line 273, in launch_image_viewer
  File "imageviewer.pyc", line 227, in __init__
  File "imageviewer.pyc", line 675, in OnOpenImage
  File "imagetools.pyc", line 50, in FetchImage
  File "imagereader.pyc", line 21, in __init__
  File "bioformats\__init__.pyc", line 174, in <module>
  File "bioformats\__init__.pyc", line 60, in start_cellprofiler_jvm
</pre>
This occurs using compiled version r20130826123052, not from source.

**Comment by AnneCarpenter** [comment]
Is this still a problem for anyone?

**Comment by PetterRanefall** [comment]
I have installed CPA 2.2.1 and there it works without copying the imagej folder, so it seems to be OK now.

**Comment by daviddao** [comment]
Great! Thanks for reporting :). I will close the issue.
