### ISSUE TITLE
CPA seg faults on Mac 10.10 (Yosemite)

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-Analyst#62]
[This Forum user](http://www.cellprofiler.org/forum/viewtopic.php?f=13&t=4111) reports that CPA (presumably release 11710?) with this error:
```
biol-lmc-0115:MacOS sstoma$ ./CPAnalyst 
Traceback (most recent call last):
  File "/Applications/CPAnalyst.app/Contents/Resources/__boot__.py", line 312, in <module>
    _run('cpa.py')
  File "/Applications/CPAnalyst.app/Contents/Resources/__boot__.py", line 309, in _run
    execfile(path, globals(), globals())
  File "/Applications/CPAnalyst.app/Contents/Resources/cpa.py", line 91, in <module>
    from classifier import Classifier
  File "classifier.pyc", line 7, in <module>
  File "datatable.pyc", line 9, in <module>
  File "imagetools.pyc", line 11, in <module>
  File "/Applications/CPAnalyst.app/Contents/Resources/lib/python2.7/matplotlib/image.py", line 21, in <module>
    import matplotlib._png as _png
ImportError: dlopen(/Applications/CPAnalyst.app/Contents/Resources/lib/python2.7/matplotlib/_png.so, 2): Library not loaded: /usr/X11/lib/libpng12.0.dylib
  Referenced from: /Applications/CPAnalyst.app/Contents/Resources/lib/python2.7/matplotlib/_png.so
  Reason: image not found
2014-12-22 17:08:24.163 CPAnalyst[3899:890307] CPAnalyst Error
Invalid memory access of location 0x60 eip=0x53ecf27
Segmentation fault: 11
```  
I asked them to try the CPA trunk build for now, but we don't have Yosemite available to test this (right?). 
(I assigned @LeeKamentsky assuming @ljosa was not available right now)

**Comment by daviddao** [comment]
CPA's <b>CPA-2.1.0-dev</b> branch (soon be merged with master) is developed and works with OS/X 10.10.
